### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by krugms00** [Razzmatazzz/RemnantSaveGuardian#170]
This only started during a recent Apocalypse campaign.  Issue is causing no world analyzer info to load for the affected character.

Error loading world Data in CharacterData.LoadWorldData: Value cannot be null. (Parameter 'key')    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, List`1 areas, Dictionary`2 allInjectables, ProcessMode mode) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1116
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1649
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1660
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 163

[save.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12596684/save.zip)

**Comment by Razzmatazzz** [comment]
This should be fixed in the latest version.
