### ISSUE TITLE
Crashing when click "save" manully and an error "An item with the same key has already been added." occurs at che check point; Can't load the buckups as well.

### ISSUE THREAD

**Issue by Hsinyuang** [Razzmatazzz/RemnantSaveGuardian#208]
System.ArgumentException 处理存档变更: An item with the same key has already been added. Key: 638365382473931828 (   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at RemnantSaveGuardian.Views.Pages.BackupsPage.getSavedBackupNames() in RemnantSaveGuardian\Views\Pages\BackupsPage.xaml.cs:line 385
   at RemnantSaveGuardian.Views.Pages.BackupsPage.doBackup() in RemnantSaveGuardian\Views\Pages\BackupsPage.xaml.cs:line 445
   at RemnantSaveGuardian.Views.Pages.BackupsPage.<SaveWatcher_SaveUpdated>b__30_0() in RemnantSaveGuardian\Views\Pages\BackupsPage.xaml.cs:line 260)

![loading all the time](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/29736062/19e88216-f019-4111-aba0-d7ead39aad18)

**Comment by ElyjahWirth** [comment]
Getting the same issue here! This can be merged with https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/228
