### ISSUE TITLE
Error when trying to read DLC adventure mode save file

### ISSUE THREAD

**Issue by jgentil** [Razzmatazzz/RemnantSaveGuardian#210]
```
Error loading world Data in CharacterData.LoadWorldData: An item with the same key has already been added. Key: Wither    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at RemnantSaveGuardian.GameInfo.RefreshGameInfo() in RemnantSaveGuardian\GameInfo.cs:line 171
   at RemnantSaveGuardian.GameInfo.get_InjectableParents() in RemnantSaveGuardian\GameInfo.cs:line 88
   at RemnantSaveGuardian.RemnantWorldEvent.GetInjectables(String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1600
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1637
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1694
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 166
```

It's a bit odd since Wither is an Aberration in Yaesha.  The Campaign tab for the save works fine but the Adventure tab doesn't highlight or isn't clickable.

**Comment by jgentil** [comment]
I also get this error:
```
Error loading world Data in CharacterData.LoadWorldData: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at RemnantSaveGuardian.GameInfo.RefreshGameInfo() in RemnantSaveGuardian\GameInfo.cs:line 171
   at RemnantSaveGuardian.GameInfo.get_InjectableParents() in RemnantSaveGuardian\GameInfo.cs:line 88
   at RemnantSaveGuardian.RemnantWorldEvent.GetInjectables(String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1600
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1637
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1694
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 166
```

**Comment by crackedmind** [comment]
Please, attach your save file.

**Comment by jgentil** [comment]
It seems that it was crashing on a second save that was in the same directory that was from a much earlier version of the game.  Removing that save fixed the issue.
