### ISSUE TITLE
World Analyzer world data loading error

### ISSUE THREAD

**Issue by Fazzl86** [Razzmatazzz/RemnantSaveGuardian#230]
Getting this error when trying to use world analyzer:

Error loading world Data in CharacterData.LoadWorldData: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1685
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1694
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 166

Any idea how to fix?

**Comment by hood-chan** [comment]
same, I was hoping to find some answers here, but I guess not a lot of people are running into this issue
