### ISSUE TITLE
World Analyzer Error: CharacterData.LoadWorldData: Index was out of range

### ISSUE THREAD

**Issue by sselicrem** [Razzmatazzz/RemnantSaveGuardian#248]
When trying to use World Analyzer I get the following error:

Error loading world Data in CharacterData.LoadWorldData: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1764
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1773
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 166

World Analyzer from profile works fine, normal World Analyzer is bugged.

[profile.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15218834/profile.zip)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/22573082/c3e9e82d-aa2d-43fd-a2ca-7cf90dabd7e3)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/22573082/5d5f905f-d562-46c2-996a-43cbde6c699a)

**Comment by sselicrem** [comment]
Resolved. I had 2 conflicting profiles in my steam saves folder (folders with numbers) and one of them was 1 year old, which was causing the issue.
