### ISSUE TITLE
Errow loading world data

### ISSUE THREAD

**Issue by misererelol** [Razzmatazzz/RemnantSaveGuardian#249]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/169047637/c32e7fcb-edd7-49c4-9094-fd25c2abd29c)

i have this message, any ideas what can i do - doesnt show me the adventure items etc..

**Comment by AndrewSav** [comment]
This seems to have already been reported here: https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/230

**Comment by blushonine** [comment]
> Need to delete the folder "RemnantSaveGuardian" (C:\Users...\AppData\Local\RemnantSaveGuardian

How did you find this out?

**Comment by misererelol** [comment]
the problem  still exist after deleting it :/

**Comment by TheNasbit** [comment]
Would have been surprised if that would have helped. Heh. I heard from others that they fixed it by generating new adventure. I would appreciate it if people with similar issues could share their save-files, so we can try to fix it.

**Comment by misererelol** [comment]
> Would have been surprised if that would have helped. Heh. I heard from others that they fixed it by generating new adventure. I would appreciate it if people with similar issues could share their save-files, so we can try to fix it.

generating 1 or 2 new adventures did fix it <3

**Comment by progital** [comment]
@TheNasbit how do I share my save file? I have this issue.

**Comment by TheNasbit** [comment]
@progital You go to your save-folder, you can quickly open it via the Save Guardian -> Go to settings, expand the "Saves" section, right click the Path of the Save Folder and click Open Folder. There you find several ".sav" Files, add them to a zip-archive, and post it here.

**Comment by progital** [comment]
```
Error loading world Data in CharacterData.LoadWorldData: The given key 'World_Jungle' was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, List`1 areas, Dictionary`2 allInjectables, ProcessMode mode) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1273
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1764
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1773
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 166
```

[save_0.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15233034/save_0.zip)

@TheNasbit please let me know if you need anything else

**Comment by Beast97544** [comment]
i got the same error like the other ones ,  in the update in december my savefiles got corrupted and i had to do a backup ... maybe its because of that

maybe someone can help me here aswell

**Comment by DarkeKnight** [comment]
I am getting the same thing, attached are my saves.

Of note, in response to progital, I have not had a save corruption issue at any point. Nor am I using mods besides the Save Guardian.

[638507001137125707.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15242172/638507001137125707.zip)

**Comment by lasdem** [comment]
I have the same Issue
[9629212.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15327539/9629212.zip)

**Comment by Fazzl86** [comment]
Any update on this yet?

**Comment by Inperual** [comment]
Hello everyone, I found a way to solve this problem, at least it worked for me, I found where my game saves are stored and deleted the folder, as a result, when I launched the game, the save from the cloud returned and the program itself began to see everything. Regarding the version of the game, Steam PC version purchased (I advise you to make a copy of your saves just in case before doing this)
