### ISSUE TITLE
Can someone help with this

### ISSUE THREAD

**Issue by chefworks69** [Razzmatazzz/RemnantSaveGuardian#259]
Error loading world Data in CharacterData.LoadWorldData: The given key 'World_Jungle' was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, List`1 areas, Dictionary`2 allInjectables, ProcessMode mode) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1273
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in RemnantSaveGuardian\RemnantWorldEvent.cs:line 1764
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in RemnantSaveGuardian\RemnantCharacter.cs:line 166

**Comment by nzgamer2** [comment]
I too have this error this morning when I rerolled my campaign. Last night I manually copying .sav files from an old folders in order to do multiple different campaign option. Could this have caused the error? 

![Screenshot 2024-05-25 075344](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/170764138/1174439e-6968-4784-8687-ceefa496063b)
